<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ManualMarriageLicenseApplication extends Model
{
    protected $fillable = [
        'control_number',
        'staff_id',
        'phone_number',
        'groom_first_name',
        'groom_middle_name',
        'groom_last_name',
        'groom_birth_date',
        'groom_age',
        'groom_birth_city',
        'groom_birth_province',
        'groom_birth_country',
        'groom_sex',
        'groom_citizenship',
        'groom_religion',
        'groom_civil_status',
        'groom_residence_address',
        'groom_dissolution_details',
        'groom_dissolution_place',
        'groom_dissolution_date',
        'groom_relationship_degree',
        'groom_father_first_name',
        'groom_father_middle_name',
        'groom_father_last_name',
        'groom_father_citizenship',
        'groom_father_residence',
        'groom_mother_first_name',
        'groom_mother_middle_name',
        'groom_mother_last_name',
        'groom_mother_citizenship',
        'groom_mother_residence',
        'groom_consent_name',
        'groom_consent_relationship',
        'groom_consent_citizenship',
        'groom_consent_residence',
        'groom_id_type',
        'groom_id_number',
        'bride_first_name',
        'bride_middle_name',
        'bride_last_name',
        'bride_birth_date',
        'bride_age',
        'bride_birth_city',
        'bride_birth_province',
        'bride_birth_country',
        'bride_sex',
        'bride_citizenship',
        'bride_religion',
        'bride_civil_status',
        'bride_residence_address',
        'bride_dissolution_details',
        'bride_dissolution_place',
        'bride_dissolution_date',
        'bride_relationship_degree',
        'bride_father_first_name',
        'bride_father_middle_name',
        'bride_father_last_name',
        'bride_father_citizenship',
        'bride_father_residence',
        'bride_mother_first_name',
        'bride_mother_middle_name',
        'bride_mother_last_name',
        'bride_mother_citizenship',
        'bride_mother_residence',
        'bride_consent_name',
        'bride_consent_relationship',
        'bride_consent_citizenship',
        'bride_consent_residence',
        'bride_id_type',
        'bride_id_number',
    ];

    protected $casts = [
        'groom_birth_date' => 'date',
        'groom_dissolution_date' => 'date',
        'bride_birth_date' => 'date',
        'bride_dissolution_date' => 'date',
    ];
}
